apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp



spec:
  replicas: 2
  
  template:
   metadata:
      name: myapp
      labels:
        app: myapp
   spec:
      containers:
        - name: myapp
          image: nginx
        - name: app
          image: tomcat:6
          
          

