apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    type: back-end



spec:
  template:
   metadata:
      name: myapp
      labels:
        app: myapp
        type: back-end
   spec:
      containers:
        - name: myapp
          image: nginx
        - name: app
          image: tomcat:6
  replicas: 1
  selector: 
     matchLabels:
       type: back-end